using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using chatbot.Core.Enums;

namespace chatbot.Core.Models
{
    public class DeviceSession:BaseEntity
    {

        public Guid UserId { get; set; } 

        public ApplicationUser User { get; set; } = null!;
        // Unique identifier generated by the client/device
        public string DeviceId { get; set; }= string.Empty;

        public string DeviceName { get; set; } = string.Empty;

        public DeviceType DeviceType { get; set; } 

        public string? IpAddress { get; set; }

        public string? UserAgent { get; set; }

        public DateTime CreatedAt { get; set; }= DateTime.UtcNow;

        public DateTime LastActivityAt { get; set; }= DateTime.UtcNow;

        public DateTime? ExpiresAt { get; set; }

        public DateTime? RevokedAt { get; set; }

        public bool IsActive { get; set; } = true;

        public ICollection<RefreshToken> RefreshTokens { get; set; }
            = new List<RefreshToken>();
    }
}
